name: docker
 
on:
 push:
   branches: [main]
 
jobs:
 docker:
   runs-on: ubuntu-latest
   permissions:
      packages: write
   steps:
     -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
     -
       name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
     -
       uses: actions/checkout@v4
     - name: Log in to the Github Container registry
       uses: docker/login-action@v3
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
     -
       name: Build and push
       uses: docker/build-push-action@v6
       with:
         context: ./
         file: ./Dockerfile
         platforms: linux/amd64,linux/arm64,linux/arm/v7
         push: true
         tags: loafoe/prometheus-watermeter-exporter:latest
